version : "3"
services:
  axe-web:
    build:
      context: .
      dockerfile: ci.Dockerfile
    container_name: axe-web
    ports:
      - "1235:80"
    restart: "no"
    networks:
      axe-network:
        ipv4_address: 11.24.1.1

  axe-pg:
    image: postgres:15
    container_name: axe-pg
    volumes:
      - axe-pg-disk:/var/lib/postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      axe-network:
        ipv4_address: 11.24.1.2

  axe-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: axe-mailpit
    restart: "no"
    networks:
      axe-network:
        ipv4_address: 11.24.1.3

# On-disk storage of DB data, when containers are stopped
volumes:
  axe-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  axe-network:
    ipam:
      driver: default
      config:
        - subnet: 11.24.0.0/16

