openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'x-web'
  description: Manage projects

paths:
  /projects/{projectId}:
    parameters:
      - name: projectId
        description: The unique identifier of the project
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ProjectId'
    get:
      summary: Read a project
      responses:
        '200':
          description: The project corresponding to the provided `projectId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        404:
          description: No project found for the provided `projectId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ProjectId:
      description: The unique identifier of a project
      type: string
    Project:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/ProjectId'
        name:
          type: string
        type:
          type: string
          enum:
            - template
            - internal
            - external
            - poc
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  x-scripts:
    HelloLogger:
      description: console.log("hello")
      type: function
  x-tests:
    StatusOkTest:
      description: pm.test('Status code is 200', function () { pm.response.to.have.status(200); });
      type: function
  x-functions:
    Incrementer:
      description: (y)=>y+1
      type: function
security:
  - bearerAuth: []
servers:
  - url: http://12.35.1.1
