version: 2.1
jobs:
  ci:
    machine: true
    resource_class: medium
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Docker compose
          command: docker-compose -f ci-docker-compose.yml up -d
      - run:
          name: CI checks
          command: docker-compose -f ci-docker-compose.yml exec axe-web composer run ci

workflows:
  version: 2
  ci-cd:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
