name: CI
on:
  push:
    paths:
      - '**/.php'
      - '**/.yml'
      - '**/.json'
      - '.env.*'
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose
        run: docker-compose -f ci-docker-compose.yml up -d
      - name: CI checks
        run: docker-compose -f ci-docker-compose.yml exec -T x-web composer run ci
